version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: flight-backend
    ports:
      - "3000:3000"
    environment:
      - DB_PROD_HOST=db
      - DB_PROD_PORT=5432
      - DB_PROD_USER=postgres
      - DB_PROD_PASS=postgres
      - DB_PROD_NAME=flight_booking_prod
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: flight-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flight_booking_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: flight-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
