name: Frontend Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Initialize Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Compile Frontend Assets
        run: npm run build
        working-directory: ./frontend
